language: ruby
cache: bundler

branches:
  only:
    - master

rvm:
 - 2.2

script:
  - git rev-parse HEAD > version.txt
  - git rev-parse --abbrev-ref HEAD > branch.txt
  - bundle exec middleman build
