dist: bionic
language: ruby
os: linux
cache: bundler

branches:
  only:
    - main
    - deploy

python:
  - 3.5

rvm:
  - 2.2

script:
  - git rev-parse HEAD > version.txt
  - git rev-parse --abbrev-ref HEAD > branch.txt
  - bundle exec middleman build
  - pip install awscli

deploy:
  - provider: s3
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    bucket: "blog.martincostello.com"
    region: eu-west-2
    skip_cleanup: true
    local_dir: build
    detect_encoding: true
    cache_control: "max-age=604800"
    on:
      branch: deploy
  - provider: lambda
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    region: "us-east-1"
    function_name: "blog-martincostello-com-redirect-folders"
    role: "arn:aws:iam::492538393790:role/service-role/lambda_basic_execution_cloudfront_edge"
    handler_name: "handler"
    module_name: "cloudfront-folders"
    timeout: 1,
    runtime: "nodejs10.x"
    zip: "cloudfront-folders.js"
    publish: true
    on:
      branch: deploy
  - provider: lambda
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    region: "us-east-1"
    function_name: "blog-martincostello-com-response-headers"
    role: "arn:aws:iam::492538393790:role/service-role/lambda_basic_execution_cloudfront_edge"
    handler_name: "handler"
    module_name: "cloudfront-headers"
    timeout: 1,
    runtime: "nodejs10.x"
    zip: "cloudfront-headers.js"
    publish: true
    on:
      branch: deploy

after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "deploy" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
