version: "{build}"

test: off

branches:
  only:
  - deploy
  - master

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby22-x64\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build_script:
  - git rev-parse HEAD > version.txt
  - git rev-parse --abbrev-ref HEAD > branch.txt
  - bundle exec middleman build

before_deploy:
  - ps: $web = Resolve-Path .\build; [IO.Directory]::GetFiles($web.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($web.Path.Length + 1).ToLowerInvariant().Replace('\', '_') -DeploymentName build }

deploy:
- provider: AzureBlob
  storage_account_name: martincostelloblog
  storage_access_key:
    secure: raoA2ntqo9xjQGca0X+Zjtbnz5xrwPa3QyVUw4SF8VSDRbpA8afv6deaZYnZv5YN9AQTL7fiG/noZLfEzvkUeP/sf2TmgIRF1WXp5KC4qKFwzL0HU19eIwe31Brpx6bK
  container: $web
  artifact: build
  set_content_type: true
  unzip: true
#  on:
#    branch: deploy
